### ISSUE TITLE
I can't get this to work

### ISSUE THREAD

**Issue by aurumvorax** [TomGrill/gdx-testing#2]
I'm not sure exactly what the problem is, I've added GdxTestRunner to my test project, used the @RunWith annotation, and my test is still generating an NPE when I try to load assets.  I tracked the error to the headless backend internal filehandler.  Before I installed your testrunner, the NPE occurred in the regular internal filehandler, not the headless one, so that much is clearly working.  Is it possible that something has broken in/before 1.9.6?  Or am I jsut doing something silly?

**Comment by TomGrill** [comment]
The testrunner does not load the libgdx environment, thats why internal filehandles are not setup like they would be in a real libgdx environment.
you need to adjust the internal path accordingly:

example:

```
@RunWith(GdxTestRunner.class)
public class AssetExistsExampleTest {

	@Test
	public void badlogicLogoFileExists() {
		assertTrue("This test will only pass when the badlogic.jpg file coming with a new project setup has not been deleted.", Gdx.files
				.internal("../android/assets/badlogic.jpg").exists());
	}
}
```

**Comment by aurumvorax** [comment]
Oh.  I thought that was the purpose of the testrunner, to provide the correct framework to run the tests in.  Anyway, I'm still not sure what path to use for testing, as I'm developing for desktop only, so my assets directory is in the core module.  I've tried the obvious "../core/assets/img/SpriteAtlas.atlas", and various permutations, without success.  Thanks for your help

**Comment by TomGrill** [comment]
The path must be relative to the working directory you run the tests in.

Just a side note: The time when I was creating this lib was in the very beginning of my libgdx career, when my mind was full of "testing is awesome"-stuff. 
Turns out that testing in game development is besides a few cases more or less useless.
The few cases you can handle by simple junit test methods. For example testing your own vector2 class.

**Comment by aurumvorax** [comment]
Thanks very much for your help.  I'm coming at things from the other side, I've written a big chunk of a game with no automated testing whatsoever(I trained in hardware/software interfaces, no unit testing on a PIC)  I mainly want to have tests to ensure that my game entities serialize/deserialize properly.
