### ISSUE TITLE
Adding tests in Intellij automatically with Alt+Enter (Create Test Dialog)

### ISSUE THREAD

**Issue by kaphula** [TomGrill/gdx-testing#4]
Hey,

Is it possible to add test classes using the Intellij's Create Test dialog while using gdx-testing?

The issue I am having is that when I alt+enter on a class that I want to create test about and accept the test creation in the Create Test dialog, the test files gets added to the "core" project instead of the "tests" project which contains all of the other tests. I have tried to set the "Destination Package" as  "de.tomgrill.gdxtesting.example", but this just creates the folder structure under "/core/src/de/..." instead of "tests/src/de..." where I assume it should be.

**Comment by TomGrill** [comment]
I think this is probably an IJ issue and can be set in settings or maybe your build.gradle. I have the same problem since years. Tell me when you got a solution :)

**Comment by kaphula** [comment]
That's unfortunate. Could this issue be solved if the source files of the tests would be placed inside the "core" project instead? Is the reason for having a separate module for gdx-testing purely aesthetic or practical?

I don't mean to pollute this repository with unrelated things to gdx-testing, but another issue I ran into was  running tests with objects that require the use of LibGDX's AssetManager. I tried to make a mock of AssetManager, but since the AssetManager will be used like: 
`assetManager.get("name.atlas", TextureAtlas.class).createSprite("sprite1");`
The tests will run into a NullPointerException during the tests. I guess loading the correct assets during the tests would be an option so that the AssetManager actually loads the correct files instead of mocks, but this would require setting the correct paths somehow for the gdx-testing module, and would that in turn break the testing process?

**Comment by TomGrill** [comment]
This repo was made when I totally jumped on the test everything train. Now I think different. Tbh I do not think this repo is of any use nowadays. Maybe I should delete it. Yeah having tests in core seems to be a valid option.

For games testing anything which is related to assets should not happen in my opinion. Those things get tested on the fly when one sees the game on the screen running. The only thing I test nowadays is game state related stuff. And even this is very rare.

**Comment by kaphula** [comment]
I see. Maybe you could turn this repository to a general guide, best practices / strategies for setting up unit testing for libgdx. I am not sure how does the editing conventions of the official libgdx wiki page work and should this information be gathered there instead.

I ended up using [this](http://manabreak.eu/java/2016/10/21/unittesting-libgdx.html) guide, which includes the tests' source files on the core module. I had issues on getting this to work earlier so that's why I decided to try gdx-testing as an alternative. The changes I needed to make in order to get the method described in the link working were:

Changing the 
`sourceSets.test.java.srcDirs = ["/tests"]
`to:
`sourceSets.test.java.srcDirs = ["src/tests"]
`
and changing the working directory of a test's run configuration as "android/assets" (similar to the 
 general libgdx desktop run configuration). This way I was able to solve the AssetManager issue since the assets are now being loaded during the tests as they would in the real application.
